FROM python:3.7

RUN mkdir -p /app
COPY requirements.txt /requirements.txt

RUN \
    apt-get update && \
    apt-get install -y -qq default-libmysqlclient-dev && \
    pip install -r /requirements.txt

EXPOSE 8000